DROP TABLE IF EXISTS qas CASCADE;
CREATE TABLE qas (
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  answer_1 TEXT NOT NULL, -- correct answer
  answer_2 TEXT NOT NULL,
  answer_3 TEXT NOT NULL,
  answer_4 TEXT NOT NULL
);
